### ISSUE TITLE
Does it work with Firefox plugins?

### ISSUE THREAD

**Issue by cong1223** [crywolfx/chrome-extension-core#1]
I read the source code, this implementation seems to be able to perfectly support Firefox browser plug-in, I understand is correct?

**Comment by crywolfx** [comment]
You can try it yourself, I don't guarantee the availability without testing.

**Comment by crywolfx** [comment]
> I read the source code, this implementation seems to be able to perfectly support Firefox browser plug-in, I understand is correct?

You can try it yourself, I don't guarantee the availability without testing.
