### ISSUE TITLE
[bug] The problem of duplicate values in an array occurs when storing it in a store.

### ISSUE THREAD

**Issue by cong1223** [crywolfx/chrome-extension-core#5]
When storing an array in a store, assuming a default value is given, the length of the array will double when retrieved next time, and the contents will be duplicated.

**Comment by cong1223** [comment]
<img width="221" alt="image" src="https://github.com/crywolfx/chrome-extension-core/assets/37927942/7019f93a-3c29-4ebb-8514-c498444ba925">
<img width="223" alt="image" src="https://github.com/crywolfx/chrome-extension-core/assets/37927942/66615912-f687-4906-b996-7b339d1baeab">
When I use useStore and store.get, the issue reoccurs after refreshing several pages.

**Comment by cong1223** [comment]
I suspect that the issue is caused by the set operation in useStore.

**Comment by crywolfx** [comment]
I'll be fixing the bug this weekend

**Comment by crywolfx** [comment]
> I suspect that the issue is caused by the set operation in useStore.
I'll be fixing the bug this weekend
